@startuml

skinparam rectangle<<PhyTxDomain>> {
	roundCorner 25
	backgroundColor Aquamarine
}

skinparam rectangle<<PhyRxDomain>> {
	roundCorner 25
	backgroundColor LightCyan
}

skinparam rectangle<<PhyRxDomain-To-SystemDomain>> {
	roundCorner 25
	backgroundColor Fuchsia
}

skinparam rectangle<<SystemDomain-To-PhyTxDomain>> {
	roundCorner 25
	backgroundColor Fuchsia
}

skinparam rectangle<<SystemDomain>> {
	roundCorner 25
	backgroundColor Gold
}


rectangle "Phy Receiver" as PhyRx <<PhyRxDomain>>
rectangle "UpConverter" as UpConv <<PhyRxDomain>>
rectangle "AsyncFIFO CDC" as CDCRx <<PhyRxDomain-To-SystemDomain>>
rectangle "Preamble check + strip" as PreRx <<SystemDomain>>
rectangle "Frame check sequence\nvalidation" as FCSRx <<SystemDomain>>
rectangle "MAC depacketizer" as PacketRx <<SystemDomain>>
rectangle "MAC sink" as Sink <<SystemDomain>>

PhyRx -down-> UpConv : PacketStream 1 ()
UpConv -down-> CDCRx : PacketStream 1 ()
CDCRx -down-> PreRx : PacketStream 4 ()
PreRx -down-> FCSRx : PacketStream 4 ()
FCSRx -down-> PacketRx : PacketStream 4 ()
PacketRx -down-> Sink : PacketStream 4 MacHeader

rectangle "MAC source" as Source <<SystemDomain>>
rectangle "Padding insert" as PaddingTx <<SystemDomain>>
rectangle "MAC Packetizer" as PacketTx <<SystemDomain>>
rectangle "Frame check sequence\ninserter" as FCSTx <<SystemDomain>>
rectangle "Preamble inserter" as PreTx <<SystemDomain>>
rectangle "AsyncFIFO CDC" as CDCTx <<SystemDomain-To-PhyTxDomain>>
rectangle "DownConverter" as DownConv <<PhyTxDomain>>
rectangle "Interpacket gap inserter" as IPG <<PhyTxDomain>>
rectangle "Phy Transmitter" as PhyTx <<PhyTxDomain>>

Source -up-> PacketTx : PacketStream 4 MacHeader
PacketTx -up-> PaddingTx : PacketStream 4 ()
PaddingTx -up-> FCSTx : PacketStream 4 ()
FCSTx -up-> PreTx : PacketStream 4 ()
PreTx -up-> CDCTx : PacketStream 4 ()
CDCTx -up-> DownConv : PacketStream 4 ()
DownConv -up-> IPG : PacketStream 1 ()
IPG -up-> PhyTx : PacketStream 1 ()

@enduml
