@startuml
skinparam rectangle<<PhyRxDomain>> {
	roundCorner 25
	backgroundColor LightCyan
}


rectangle "Phy Receiver" as PhyRx <<PhyRxDomain>>
rectangle "Phy Transmitter" as PhyTx <<PhyRxDomain>>
rectangle "Stream FIFO" as StreamFIFO <<PhyRxDomain>>
rectangle "Packet Buffer" as PacketBuf <<PhyRxDomain>>
rectangle "UART transmitter" as UARTTx <<PhyRxDomain>>
rectangle "UART reciever" as UARTRx <<PhyRxDomain>>

PhyRx -down-> StreamFIFO : PacketStream 1 ()
StreamFIFO -down-> UARTTx : PacketStream 1 ()

UARTRx -up-> PacketBuf :PacketStream 1 ()
PacketBuf -up-> PhyTx : PacketStream 1 ()
@enduml
