name: "Linters"
on: [push, pull_request]
jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: Whitespace file endings
        run: .ci/test_whitespace.sh
      - name: Run haskell formatter 
        run: |
        	cp ./.stylish-haskell.yaml ./.stylish-haskell-check.yaml
          echo "exit_code: error_on_format" >> ./.stylish-haskell-check.yaml
          curl -sL https://raw.github.com/haskell/stylish-haskell/master/scripts/latest.sh | sh -s -c ./.stylish-haskell-check.yaml -r src tests
      - name: Clean-up after stylish haskell
        run: rm ./.stylish-haskell-check.yaml
