name: "CI pipeline"
on:
  push:
jobs:
  check_nix:
    runs-on: ubuntu-latest
    steps:
    - name: git checkout
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - name: run "nix-shell"
    - run: nix-shell

  build_and_test:
    runs-on: ubuntu-latest
    needs: check_nix
    steps:
      - name: git checkout
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: make test
      - run: make test