name: "CI pipeline"
on:
  push:
    branches: [ develop ]
jobs:
  build_and_synthesize:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: check formatting
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: baublesaurus/clockbox:latest
          options: -v ${{ github.workspace }}:/work
          run: |
            mkdir /tmp
            cd work
            # check formating
            make check_format
      - name: test-library
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: baublesaurus/clockbox:latest
          options: -v ${{ github.workspace }}:/work
          run: |
            mkdir /tmp
            cd work
            cabal test test-library --test-show-details=streaming
      - name: Synthesize-clash
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: baublesaurus/clockbox:latest
          options: -v ${{ github.workspace }}:/work
          run: |
            mkdir /tmp
            cd work
            make verilog
      - name: Synthesize
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: baublesaurus/clockbox:latest
          options: -v ${{ github.workspace }}:/work
          run: |
            mkdir /tmp
            cd work
            make netlist
      - name: Place-and-route
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: baublesaurus/clockbox:latest
          options: -v ${{ github.workspace }}:/work
          run: |
            mkdir /tmp
            cd work
            make pnr
